[2023-03-10T23:12:15.175+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ufrn_etl.run_intake_docentes scheduled__2023-03-09T00:00:00+00:00 [queued]>
[2023-03-10T23:12:15.189+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ufrn_etl.run_intake_docentes scheduled__2023-03-09T00:00:00+00:00 [queued]>
[2023-03-10T23:12:15.189+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-10T23:12:15.189+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-03-10T23:12:15.189+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-10T23:12:15.210+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): run_intake_docentes> on 2023-03-09 00:00:00+00:00
[2023-03-10T23:12:15.219+0000] {standard_task_runner.py:55} INFO - Started process 428 to run task
[2023-03-10T23:12:15.223+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ufrn_etl', 'run_intake_docentes', 'scheduled__2023-03-09T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/ufrn_dag.py', '--cfg-path', '/tmp/tmplekhmzhk']
[2023-03-10T23:12:15.225+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask run_intake_docentes
[2023-03-10T23:12:15.300+0000] {task_command.py:388} INFO - Running <TaskInstance: ufrn_etl.run_intake_docentes scheduled__2023-03-09T00:00:00+00:00 [running]> on host 68d82db6eea0
[2023-03-10T23:12:15.377+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=breno.nahuz@discente.ufma.br
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ufrn_etl
AIRFLOW_CTX_TASK_ID=run_intake_docentes
AIRFLOW_CTX_EXECUTION_DATE=2023-03-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-09T00:00:00+00:00
[2023-03-10T23:12:15.379+0000] {logging_mixin.py:137} INFO - [INFO] - Getting data from https://dados.ufrn.br/dataset/8bf1a468-48ff-4f4d-95ee-b17b7a3a5592/resource/6a8e5461-e748-45c6-aac6-432188d88dde/download/docentes.csv
[2023-03-10T23:12:17.036+0000] {python.py:177} INFO - Done. Returned value was:         siape  ...                       admissao
0     1543339  ...  2006/07/24 00:00:00.000000000
1     1554468  ...  2008/09/12 00:00:00.000000000
2     1177821  ...  1998/04/28 00:00:00.000000000
3     2360824  ...  2017/01/25 00:00:00.000000000
4     2364334  ...  2009/10/13 00:00:00.000000000
...       ...  ...                            ...
2680  3305981  ...  2022/08/29 00:00:00.000000000
2681  6209696  ...  2022/08/12 00:00:00.000000000
2682  3304576  ...  2022/08/12 00:00:00.000000000
2683  1056188  ...  2022/10/03 00:00:00.000000000
2684  3309092  ...  2022/09/06 00:00:00.000000000

[2685 rows x 11 columns]
[2023-03-10T23:12:17.267+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-03-10T23:12:17.269+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-03-10T23:12:17.286+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=ufrn_etl, task_id=run_intake_docentes, execution_date=20230309T000000, start_date=20230310T231215, end_date=20230310T231217
[2023-03-10T23:12:17.304+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 11 for task run_intake_docentes (Object of type DataFrame is not JSON serializable; 428)
[2023-03-10T23:12:17.323+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-10T23:12:17.393+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
